# Generated by Django 5.0.6 on 2026-03-01 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('passwordd', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Pending Approval', 'Pending Approval')], default='Pending Approval', max_length=50, null=True)),
                ('regdate', models.DateField(auto_now_add=True, null=True)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('is_login', models.CharField(blank=True, max_length=255, null=True)),
                ('user_session', models.CharField(blank=True, max_length=255, null=True)),
                ('is_multi_user', models.CharField(blank=True, choices=[('False', 'Single User'), ('True', 'Multi User')], max_length=50, null=True)),
                ('founder_member', models.CharField(blank=True, choices=[('NO', 'NO'), ('Founder Member', 'Founder Member')], default='NO', max_length=50, null=True)),
                ('founder_member_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('tsr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_page_view', models.IntegerField(blank=True, default='100', null=True)),
                ('user_monthly_page_view', models.IntegerField(blank=True, default='0', null=True)),
                ('user_page_view_month', models.IntegerField(blank=True, default='0', null=True)),
                ('is_salesman', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_future', models.BooleanField(default=False)),
                ('is_ai_web', models.BooleanField(default=False)),
                ('monthly_ai_page_view', models.IntegerField(blank=True, default='100', null=True)),
                ('ai_monthly_page_view', models.IntegerField(blank=True, default='0', null=True)),
                ('ai_page_view_month', models.IntegerField(blank=True, default='0', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_salesmen', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='SalesmanUser',
            fields=[
            ],
            options={
                'verbose_name': 'Salesman',
                'verbose_name_plural': 'Salesmens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('login_auth.user',),
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending Approval', 'Pending Approval')], default='Pending Approval', max_length=50)),
                ('valid_date', models.DateField(blank=True, null=True)),
                ('founder_member_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('tsr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('token_jti', models.TextField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidation_reason', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='login_auth__user_id_225df8_idx'), models.Index(fields=['token_jti'], name='login_auth__token_j_9a96ea_idx'), models.Index(fields=['invalidated_at'], name='login_auth__invalid_bab794_idx')],
            },
        ),
    ]
