# Generated by Django 5.0.6 on 2026-03-12 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('count', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_text', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='roadmap/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='planfeature',
            name='plan',
        ),
        migrations.DeleteModel(
            name='ServicePage',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='billing_period',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='button_url',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pricingplan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='icon',
            field=models.ImageField(default='', upload_to='pricing_icons/'),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='monthly_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='services',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='yearly_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pricingplan',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.pricingplan'),
        ),
        migrations.DeleteModel(
            name='PlanFeature',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
