# Generated by Django 5.0.6 on 2026-03-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_counterboard_pricingfeature_roadmapstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prefix', models.CharField(max_length=200)),
                ('word_one', models.CharField(max_length=100)),
                ('word_two', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('button_one_text', models.CharField(max_length=100)),
                ('button_one_link', models.CharField(max_length=200)),
                ('button_two_text', models.CharField(max_length=100)),
                ('button_two_link', models.CharField(max_length=200)),
                ('video_mp4', models.FileField(upload_to='banner_videos/')),
                ('video_ogg', models.FileField(blank=True, null=True, upload_to='banner_videos/')),
            ],
        ),
    ]
