# Generated by Django 5.0.6 on 2026-03-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='button_two_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_two_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
