# Generated by Django 5.0.6 on 2026-03-14 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_legalcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQPage',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
    ]
