# Generated by Django 5.0.6 on 2026-03-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_faqpage_alter_faq_options_remove_faq_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='PricingPage',
        ),
    ]
