# Generated by Django 5.0.6 on 2026-03-16 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_agent_delete_contactpage_delete_pricingpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('legal_name', models.TextField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('gst', models.CharField(blank=True, max_length=15, null=True)),
                ('gst_amount', models.TextField(blank=True, null=True)),
                ('payable_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('txnid', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_txnid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('resp_code', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_name', models.CharField(blank=True, max_length=255, null=True)),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_salesman', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_payemnt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-pk'],
            },
        ),
    ]
