# Generated by Django 5.0.6 on 2026-03-21 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tblpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('category', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('ai_answer', models.TextField()),
                ('source_bot', models.CharField(choices=[('main', 'Main'), ('premium', 'Premium'), ('free', 'Free')], default='main', max_length=30)),
                ('is_detailed', models.BooleanField(default=False)),
                ('planner_output', models.JSONField(blank=True, null=True)),
                ('sources_used', models.JSONField(blank=True, null=True)),
                ('sources_shown', models.JSONField(blank=True, null=True)),
                ('web_context', models.TextField(blank=True, null=True)),
                ('verification', models.JSONField(blank=True, null=True)),
                ('was_resynthesized', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('query_time_ms', models.IntegerField(default=0)),
                ('web_search_used', models.BooleanField(default=True)),
                ('max_results', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.aichatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='aichatsession',
            index=models.Index(fields=['session_token'], name='idx_sessions_token'),
        ),
    ]
