# Generated by Django 5.0.6 on 2026-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aichatsession_aichatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=250),
        ),
    ]
