# Generated by Django 5.1 on 2026-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_aichatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichatsession',
            name='model_type',
            field=models.CharField(choices=[('ask_bot', 'Ask Bot'), ('case_law_research', 'Case Law Research'), ('summarizer', 'Summarizer'), ('draft_assistant', 'Draft Assistant')], db_index=True, default='ask_bot', max_length=30),
        ),
    ]
